// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package hyperliquid

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid(in *jlexer.Lexer, out *remoteWebData3SubscriptionPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "user":
			if in.IsNull() {
				in.Skip()
			} else {
				out.User = string(in.String())
			}
		case "dex":
			if in.IsNull() {
				in.Skip()
				out.Dex = nil
			} else {
				if out.Dex == nil {
					out.Dex = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Dex = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid(out *jwriter.Writer, in remoteWebData3SubscriptionPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"user\":"
		out.RawString(prefix)
		out.String(string(in.User))
	}
	if in.Dex != nil {
		const prefix string = ",\"dex\":"
		out.RawString(prefix)
		out.String(string(*in.Dex))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v remoteWebData3SubscriptionPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v remoteWebData3SubscriptionPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *remoteWebData3SubscriptionPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *remoteWebData3SubscriptionPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid(l, v)
}
func easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid1(in *jlexer.Lexer, out *remoteWebData2SubscriptionPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "user":
			if in.IsNull() {
				in.Skip()
			} else {
				out.User = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid1(out *jwriter.Writer, in remoteWebData2SubscriptionPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"user\":"
		out.RawString(prefix)
		out.String(string(in.User))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v remoteWebData2SubscriptionPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v remoteWebData2SubscriptionPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *remoteWebData2SubscriptionPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *remoteWebData2SubscriptionPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid1(l, v)
}
func easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid2(in *jlexer.Lexer, out *remoteTwapStatesSubscriptionPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "user":
			if in.IsNull() {
				in.Skip()
			} else {
				out.User = string(in.String())
			}
		case "dex":
			if in.IsNull() {
				in.Skip()
				out.Dex = nil
			} else {
				if out.Dex == nil {
					out.Dex = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Dex = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid2(out *jwriter.Writer, in remoteTwapStatesSubscriptionPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"user\":"
		out.RawString(prefix)
		out.String(string(in.User))
	}
	if in.Dex != nil {
		const prefix string = ",\"dex\":"
		out.RawString(prefix)
		out.String(string(*in.Dex))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v remoteTwapStatesSubscriptionPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v remoteTwapStatesSubscriptionPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *remoteTwapStatesSubscriptionPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *remoteTwapStatesSubscriptionPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid2(l, v)
}
func easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid3(in *jlexer.Lexer, out *remoteTradesSubscriptionPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Coin = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid3(out *jwriter.Writer, in remoteTradesSubscriptionPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix)
		out.String(string(in.Coin))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v remoteTradesSubscriptionPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v remoteTradesSubscriptionPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *remoteTradesSubscriptionPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *remoteTradesSubscriptionPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid3(l, v)
}
func easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid4(in *jlexer.Lexer, out *remoteOrderUpdatesSubscriptionPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "user":
			if in.IsNull() {
				in.Skip()
			} else {
				out.User = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid4(out *jwriter.Writer, in remoteOrderUpdatesSubscriptionPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"user\":"
		out.RawString(prefix)
		out.String(string(in.User))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v remoteOrderUpdatesSubscriptionPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v remoteOrderUpdatesSubscriptionPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *remoteOrderUpdatesSubscriptionPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *remoteOrderUpdatesSubscriptionPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid4(l, v)
}
func easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid5(in *jlexer.Lexer, out *remoteOrderFillsSubscriptionPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "user":
			if in.IsNull() {
				in.Skip()
			} else {
				out.User = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid5(out *jwriter.Writer, in remoteOrderFillsSubscriptionPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"user\":"
		out.RawString(prefix)
		out.String(string(in.User))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v remoteOrderFillsSubscriptionPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v remoteOrderFillsSubscriptionPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *remoteOrderFillsSubscriptionPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *remoteOrderFillsSubscriptionPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid5(l, v)
}
func easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid6(in *jlexer.Lexer, out *remoteOpenOrdersSubscriptionPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "user":
			if in.IsNull() {
				in.Skip()
			} else {
				out.User = string(in.String())
			}
		case "dex":
			if in.IsNull() {
				in.Skip()
				out.Dex = nil
			} else {
				if out.Dex == nil {
					out.Dex = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Dex = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid6(out *jwriter.Writer, in remoteOpenOrdersSubscriptionPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"user\":"
		out.RawString(prefix)
		out.String(string(in.User))
	}
	if in.Dex != nil {
		const prefix string = ",\"dex\":"
		out.RawString(prefix)
		out.String(string(*in.Dex))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v remoteOpenOrdersSubscriptionPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v remoteOpenOrdersSubscriptionPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *remoteOpenOrdersSubscriptionPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *remoteOpenOrdersSubscriptionPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid6(l, v)
}
func easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid7(in *jlexer.Lexer, out *remoteNotificationSubscriptionPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "user":
			if in.IsNull() {
				in.Skip()
			} else {
				out.User = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid7(out *jwriter.Writer, in remoteNotificationSubscriptionPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"user\":"
		out.RawString(prefix)
		out.String(string(in.User))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v remoteNotificationSubscriptionPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v remoteNotificationSubscriptionPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *remoteNotificationSubscriptionPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *remoteNotificationSubscriptionPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid7(l, v)
}
func easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid8(in *jlexer.Lexer, out *remoteL2BookSubscriptionPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Coin = string(in.String())
			}
		case "nSigFigs":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NSigFigs = int(in.Int())
			}
		case "mantissa":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Mantissa = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid8(out *jwriter.Writer, in remoteL2BookSubscriptionPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix)
		out.String(string(in.Coin))
	}
	if in.NSigFigs != 0 {
		const prefix string = ",\"nSigFigs\":"
		out.RawString(prefix)
		out.Int(int(in.NSigFigs))
	}
	if in.Mantissa != 0 {
		const prefix string = ",\"mantissa\":"
		out.RawString(prefix)
		out.Int(int(in.Mantissa))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v remoteL2BookSubscriptionPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v remoteL2BookSubscriptionPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *remoteL2BookSubscriptionPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *remoteL2BookSubscriptionPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid8(l, v)
}
func easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid9(in *jlexer.Lexer, out *remoteClearinghouseStateSubscriptionPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "user":
			if in.IsNull() {
				in.Skip()
			} else {
				out.User = string(in.String())
			}
		case "dex":
			if in.IsNull() {
				in.Skip()
				out.Dex = nil
			} else {
				if out.Dex == nil {
					out.Dex = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Dex = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid9(out *jwriter.Writer, in remoteClearinghouseStateSubscriptionPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"user\":"
		out.RawString(prefix)
		out.String(string(in.User))
	}
	if in.Dex != nil {
		const prefix string = ",\"dex\":"
		out.RawString(prefix)
		out.String(string(*in.Dex))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v remoteClearinghouseStateSubscriptionPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v remoteClearinghouseStateSubscriptionPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *remoteClearinghouseStateSubscriptionPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *remoteClearinghouseStateSubscriptionPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid9(l, v)
}
func easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid10(in *jlexer.Lexer, out *remoteCandlesSubscriptionPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Coin = string(in.String())
			}
		case "interval":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Interval = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid10(out *jwriter.Writer, in remoteCandlesSubscriptionPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix)
		out.String(string(in.Coin))
	}
	{
		const prefix string = ",\"interval\":"
		out.RawString(prefix)
		out.String(string(in.Interval))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v remoteCandlesSubscriptionPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v remoteCandlesSubscriptionPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *remoteCandlesSubscriptionPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *remoteCandlesSubscriptionPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid10(l, v)
}
func easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid11(in *jlexer.Lexer, out *remoteBboSubscriptionPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Coin = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid11(out *jwriter.Writer, in remoteBboSubscriptionPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix)
		out.String(string(in.Coin))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v remoteBboSubscriptionPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v remoteBboSubscriptionPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *remoteBboSubscriptionPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *remoteBboSubscriptionPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid11(l, v)
}
func easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid12(in *jlexer.Lexer, out *remoteAllMidsSubscriptionPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "dex":
			if in.IsNull() {
				in.Skip()
				out.Dex = nil
			} else {
				if out.Dex == nil {
					out.Dex = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Dex = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid12(out *jwriter.Writer, in remoteAllMidsSubscriptionPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	if in.Dex != nil {
		const prefix string = ",\"dex\":"
		out.RawString(prefix)
		out.String(string(*in.Dex))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v remoteAllMidsSubscriptionPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v remoteAllMidsSubscriptionPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *remoteAllMidsSubscriptionPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *remoteAllMidsSubscriptionPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid12(l, v)
}
func easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid13(in *jlexer.Lexer, out *remoteActiveAssetCtxSubscriptionPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Coin = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid13(out *jwriter.Writer, in remoteActiveAssetCtxSubscriptionPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix)
		out.String(string(in.Coin))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v remoteActiveAssetCtxSubscriptionPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v remoteActiveAssetCtxSubscriptionPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6658546bEncodeGithubCom0xsyndrGoHyperliquid13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *remoteActiveAssetCtxSubscriptionPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *remoteActiveAssetCtxSubscriptionPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6658546bDecodeGithubCom0xsyndrGoHyperliquid13(l, v)
}
